//_\TLV_version 1d: tl-x.org, generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro
//_\source scorer.tlv 3
//_\SV
   module tt_um_hale_attn_scorer (
     input  wire [7:0] ui_in,
     output wire [7:0] uo_out,
     input  wire [7:0] uio_in,
     output wire [7:0] uio_out,
     output wire [7:0] uio_oe,
     input  wire       ena,
     input  wire       clk,
     input  wire       rst_n
   );
   assign uio_out = 8'b0;
   assign uio_oe  = 8'b0;
   wire reset = ~rst_n;
// ---------- Generated Code Inlined Here (before 1st \TLV) ----------
// Generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro from Redwood EDA, LLC.
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)





//
// Signals declared top-level.
//

// For |scorer$acc.
logic [15:0] SCORER_acc_n1,
             SCORER_acc_a0;

// For |scorer$acc_full.
logic [15:0] SCORER_acc_full_a0;

// For |scorer$acc_next.
logic [15:0] SCORER_acc_next_a0;

// For |scorer$acc_temp.
logic [16:0] SCORER_acc_temp_a0;

// For |scorer$best.
logic [15:0] SCORER_best_n1,
             SCORER_best_a0;

// For |scorer$best_idx.
logic [5:0] SCORER_best_idx_n1,
            SCORER_best_idx_a0;

// For |scorer$best_idx_next.
logic [5:0] SCORER_best_idx_next_a0;

// For |scorer$best_next.
logic [15:0] SCORER_best_next_a0;

// For |scorer$cmd.
logic [1:0] SCORER_cmd_a0;

// For |scorer$data.
logic [7:0] SCORER_data_a0;

// For |scorer$dim.
logic [3:0] SCORER_dim_n1,
            SCORER_dim_a0;

// For |scorer$dim_next.
logic [3:0] SCORER_dim_next_a0;

// For |scorer$inc_dim.
logic SCORER_inc_dim_a0;

// For |scorer$is_idle.
logic SCORER_is_idle_a0;

// For |scorer$is_load_q.
logic SCORER_is_load_q_a0;

// For |scorer$is_read.
logic SCORER_is_read_a0;

// For |scorer$is_stream_k.
logic SCORER_is_stream_k_a0;

// For |scorer$key_idx.
logic [5:0] SCORER_key_idx_n1,
            SCORER_key_idx_a0;

// For |scorer$key_idx_next.
logic [5:0] SCORER_key_idx_next_a0;

// For |scorer$load_complete.
logic SCORER_load_complete_a0;

// For |scorer$load_q_write.
logic SCORER_load_q_write_a0;

// For |scorer$out.
logic [7:0] SCORER_out_n1,
            SCORER_out_a0;

// For |scorer$out_next.
logic [7:0] SCORER_out_next_a0;

// For |scorer$prod.
logic [15:0] SCORER_prod_a0;

// For |scorer$q0.
logic [7:0] SCORER_q0_n1,
            SCORER_q0_a0;

// For |scorer$q1.
logic [7:0] SCORER_q1_n1,
            SCORER_q1_a0;

// For |scorer$q2.
logic [7:0] SCORER_q2_n1,
            SCORER_q2_a0;

// For |scorer$q3.
logic [7:0] SCORER_q3_n1,
            SCORER_q3_a0;

// For |scorer$q4.
logic [7:0] SCORER_q4_n1,
            SCORER_q4_a0;

// For |scorer$q5.
logic [7:0] SCORER_q5_n1,
            SCORER_q5_a0;

// For |scorer$q6.
logic [7:0] SCORER_q6_n1,
            SCORER_q6_a0;

// For |scorer$q7.
logic [7:0] SCORER_q7_n1,
            SCORER_q7_a0;

// For |scorer$q_idx.
logic [2:0] SCORER_q_idx_a0;

// For |scorer$qfill.
logic [3:0] SCORER_qfill_n1,
            SCORER_qfill_a0;

// For |scorer$qfill_next.
logic [3:0] SCORER_qfill_next_a0;

// For |scorer$qsel.
logic [7:0] SCORER_qsel_a0;

// For |scorer$read_phase.
logic [1:0] SCORER_read_phase_n1,
            SCORER_read_phase_a0;

// For |scorer$read_phase_next.
logic [1:0] SCORER_read_phase_next_a0;

// For |scorer$reset_acc_dim.
logic SCORER_reset_acc_dim_a0;




   //
   // Scope: |scorer
   //

      // Staging of $acc.
      always_ff @(posedge clk) SCORER_acc_a0[15:0] <= SCORER_acc_n1[15:0];

      // Staging of $best.
      always_ff @(posedge clk) SCORER_best_a0[15:0] <= SCORER_best_n1[15:0];

      // Staging of $best_idx.
      always_ff @(posedge clk) SCORER_best_idx_a0[5:0] <= SCORER_best_idx_n1[5:0];

      // Staging of $dim.
      always_ff @(posedge clk) SCORER_dim_a0[3:0] <= SCORER_dim_n1[3:0];

      // Staging of $key_idx.
      always_ff @(posedge clk) SCORER_key_idx_a0[5:0] <= SCORER_key_idx_n1[5:0];

      // Staging of $out.
      always_ff @(posedge clk) SCORER_out_a0[7:0] <= SCORER_out_n1[7:0];

      // Staging of $q0.
      always_ff @(posedge clk) SCORER_q0_a0[7:0] <= SCORER_q0_n1[7:0];

      // Staging of $q1.
      always_ff @(posedge clk) SCORER_q1_a0[7:0] <= SCORER_q1_n1[7:0];

      // Staging of $q2.
      always_ff @(posedge clk) SCORER_q2_a0[7:0] <= SCORER_q2_n1[7:0];

      // Staging of $q3.
      always_ff @(posedge clk) SCORER_q3_a0[7:0] <= SCORER_q3_n1[7:0];

      // Staging of $q4.
      always_ff @(posedge clk) SCORER_q4_a0[7:0] <= SCORER_q4_n1[7:0];

      // Staging of $q5.
      always_ff @(posedge clk) SCORER_q5_a0[7:0] <= SCORER_q5_n1[7:0];

      // Staging of $q6.
      always_ff @(posedge clk) SCORER_q6_a0[7:0] <= SCORER_q6_n1[7:0];

      // Staging of $q7.
      always_ff @(posedge clk) SCORER_q7_a0[7:0] <= SCORER_q7_n1[7:0];

      // Staging of $qfill.
      always_ff @(posedge clk) SCORER_qfill_a0[3:0] <= SCORER_qfill_n1[3:0];

      // Staging of $read_phase.
      always_ff @(posedge clk) SCORER_read_phase_a0[1:0] <= SCORER_read_phase_n1[1:0];



// ---------- Generated Code Ends ----------
//_\TLV
   //_|scorer
      //_@0
         // Inputs
         assign SCORER_cmd_a0[1:0]        = uio_in[1:0];
         assign SCORER_data_a0[7:0]       = ui_in;

         // Command decode
         assign SCORER_is_idle_a0         = (SCORER_cmd_a0 == 2'b00);
         assign SCORER_is_load_q_a0       = (SCORER_cmd_a0 == 2'b01);
         assign SCORER_is_stream_k_a0     = (SCORER_cmd_a0 == 2'b10);
         assign SCORER_is_read_a0         = (SCORER_cmd_a0 == 2'b11);

         // Query buffer: 8 separate flops
         assign SCORER_qsel_a0[7:0]       = (SCORER_dim_a0 == 0) ? SCORER_q0_a0 : (SCORER_dim_a0 == 1) ? SCORER_q1_a0 : (SCORER_dim_a0 == 2) ? SCORER_q2_a0 : (SCORER_dim_a0 == 3) ? SCORER_q3_a0 :
                            (SCORER_dim_a0 == 4) ? SCORER_q4_a0 : (SCORER_dim_a0 == 5) ? SCORER_q5_a0 : (SCORER_dim_a0 == 6) ? SCORER_q6_a0 : SCORER_q7_a0;
         assign SCORER_load_q_write_a0    = SCORER_is_load_q_a0;
         assign SCORER_q_idx_a0[2:0]      = (SCORER_qfill_a0 >= 8) ? 3'b0 : SCORER_qfill_a0[2:0];

         // qfill (next state)
         assign SCORER_qfill_next_a0[3:0] = reset ? 4'b0 :
                            SCORER_is_load_q_a0 ? ((SCORER_qfill_a0 >= 8) ? 4'd1 : SCORER_qfill_a0 + 1'd1) :
                            (SCORER_qfill_a0 < 8) ? 4'b0 : SCORER_qfill_a0;

         // Query byte loading
         assign SCORER_q0_n1[7:0]      = reset ? 8'b0 : (SCORER_load_q_write_a0 && SCORER_q_idx_a0 == 0) ? SCORER_data_a0 : SCORER_q0_a0;
         assign SCORER_q1_n1[7:0]      = reset ? 8'b0 : (SCORER_load_q_write_a0 && SCORER_q_idx_a0 == 1) ? SCORER_data_a0 : SCORER_q1_a0;
         assign SCORER_q2_n1[7:0]      = reset ? 8'b0 : (SCORER_load_q_write_a0 && SCORER_q_idx_a0 == 2) ? SCORER_data_a0 : SCORER_q2_a0;
         assign SCORER_q3_n1[7:0]      = reset ? 8'b0 : (SCORER_load_q_write_a0 && SCORER_q_idx_a0 == 3) ? SCORER_data_a0 : SCORER_q3_a0;
         assign SCORER_q4_n1[7:0]      = reset ? 8'b0 : (SCORER_load_q_write_a0 && SCORER_q_idx_a0 == 4) ? SCORER_data_a0 : SCORER_q4_a0;
         assign SCORER_q5_n1[7:0]      = reset ? 8'b0 : (SCORER_load_q_write_a0 && SCORER_q_idx_a0 == 5) ? SCORER_data_a0 : SCORER_q5_a0;
         assign SCORER_q6_n1[7:0]      = reset ? 8'b0 : (SCORER_load_q_write_a0 && SCORER_q_idx_a0 == 6) ? SCORER_data_a0 : SCORER_q6_a0;
         assign SCORER_q7_n1[7:0]      = reset ? 8'b0 : (SCORER_load_q_write_a0 && SCORER_q_idx_a0 == 7) ? SCORER_data_a0 : SCORER_q7_a0;
         assign SCORER_qfill_n1[3:0]   = SCORER_qfill_next_a0;

         // Load complete detection (resets best/idx/key_idx)
         assign SCORER_load_complete_a0    = SCORER_is_load_q_a0 && (SCORER_qfill_a0 == 7);

         // Accumulator and dimension
         assign SCORER_reset_acc_dim_a0   = SCORER_is_load_q_a0 || SCORER_is_idle_a0;
         assign SCORER_inc_dim_a0         = SCORER_is_stream_k_a0 && (SCORER_key_idx_a0 <= 63);
         assign SCORER_prod_a0[15:0]      = $signed(SCORER_qsel_a0) * $signed(SCORER_data_a0);
         assign SCORER_acc_temp_a0[16:0]  = $signed(SCORER_acc_a0) + $signed(SCORER_prod_a0);
         assign SCORER_acc_full_a0[15:0]  = (SCORER_acc_temp_a0[16:15] == 2'b01) ? 16'h7FFF :
                            (SCORER_acc_temp_a0[16:15] == 2'b10) ? 16'h8000 : SCORER_acc_temp_a0[15:0];
         assign SCORER_dim_next_a0[3:0]   = reset ? 4'b0 :
                            (SCORER_reset_acc_dim_a0 || (SCORER_inc_dim_a0 && SCORER_dim_a0 == 7)) ? 4'b0 :
                            SCORER_inc_dim_a0 ? SCORER_dim_a0 + 1'd1 : SCORER_dim_a0;
         assign SCORER_acc_next_a0[15:0]  = reset ? 16'b0 :
                            (SCORER_reset_acc_dim_a0 || (SCORER_inc_dim_a0 && SCORER_dim_a0 == 7)) ? 16'b0 :
                            SCORER_inc_dim_a0 ? SCORER_acc_full_a0 : SCORER_acc_a0;
         assign SCORER_dim_n1[3:0]     = SCORER_dim_next_a0;
         assign SCORER_acc_n1[15:0]    = SCORER_acc_next_a0;

         // Key index, best score, best index
         assign SCORER_key_idx_next_a0[5:0] = reset ? 6'b0 :
                              SCORER_load_complete_a0 ? 6'b0 :
                              (SCORER_inc_dim_a0 && SCORER_dim_a0 == 7 && SCORER_key_idx_a0 <= 63) ? (SCORER_key_idx_a0 + 1'd1) : SCORER_key_idx_a0;
         assign SCORER_best_next_a0[15:0]   = reset ? 16'h8000 : // -32768
                              SCORER_load_complete_a0 ? 16'h8000 :
                              (SCORER_inc_dim_a0 && SCORER_dim_a0 == 7 && SCORER_key_idx_a0 <= 63 && ($signed(SCORER_acc_full_a0) > $signed(SCORER_best_a0))) ? SCORER_acc_full_a0 : SCORER_best_a0;
         assign SCORER_best_idx_next_a0[5:0] = reset ? 6'b0 :
                               SCORER_load_complete_a0 ? 6'b0 :
                               (SCORER_inc_dim_a0 && SCORER_dim_a0 == 7 && SCORER_key_idx_a0 <= 63 && ($signed(SCORER_acc_full_a0) > $signed(SCORER_best_a0))) ? SCORER_key_idx_a0 : SCORER_best_idx_a0;
         assign SCORER_key_idx_n1[5:0]    = SCORER_key_idx_next_a0;
         assign SCORER_best_n1[15:0]      = SCORER_best_next_a0;
         assign SCORER_best_idx_n1[5:0]   = SCORER_best_idx_next_a0;

         // Read phase and output
         assign SCORER_read_phase_next_a0[1:0] = reset ? 2'b0 :
                                 SCORER_is_read_a0 ? ((SCORER_read_phase_a0 == 2) ? 2'b0 : SCORER_read_phase_a0 + 1'd1) : 2'b0;
         assign SCORER_out_next_a0[7:0]        = reset ? 8'b0 :
                                 SCORER_is_read_a0 ? ((SCORER_read_phase_a0 == 2'b00) ? SCORER_best_idx_a0[5:0] :
                                             (SCORER_read_phase_a0 == 2'b01) ? SCORER_best_a0[15:8] : SCORER_best_a0[7:0]) : SCORER_out_a0;
         assign SCORER_read_phase_n1[1:0]   = SCORER_read_phase_next_a0;
         assign SCORER_out_n1[7:0]          = SCORER_out_next_a0;

         // Output assignment
         assign uo_out = SCORER_out_a0;
//_\SV
   endmodule


// Undefine macros defined by SandPiper.
`undef BOGUS_USE
